apiVersion: v1
kind: Secret
metadata:
  labels:
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-config"
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
        name: {{ .Release.Name }}-preflight
    spec:
      collectors:
      - clusterResources: {}
      analyzers:
        - clusterVersion:
            outcomes:
            - fail:
                when: "< 1.13.0"
                message: The application requires at Kubernetes 1.13.0 or later, and recommends 1.15.0.
                uri: https://www.kubernetes.io
            - warn:
                when: "< 1.15.0"
                message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.15.0 or later.
                uri: https://kubernetes.io
            - pass:
                message: Your cluster meets the recommended and required versions of Kubernetes.
