name: App Release
on:
  push:
    branches: [main]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Define App Version
      shell: bash
      run: echo "APP_VERSION=0.1.0-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Package Helm Chart for Replicated
      id: package-helm-chart
      run: |
        mkdir -p manifests
        helm package ./gitea -u -d manifests \
          --app-version=0.0.1-${{ github.ref_name }} \
          --version=${{ env.APP_VERSION }}

    - name: Create Release
      uses: docker://replicated/vendor-cli:latest
      with:
        args: release create --promote=Unstable --version=${{ env.APP_VERSION }} --yaml-dir=manifests
      env:
        REPLICATED_API_TOKEN: ${{ secrets.REPLICATED_API_TOKEN }}
        REPLICATED_APP: ${{ secrets.REPLICATED_APP }}

  compatibility-matrix:
    strategy:
      fail-fast: false
      matrix:
        cluster: [ {distribution: kind, version: v1.25.3}, {distribution: k3s, version: v1.26}]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Define App Version
      shell: bash
      run: echo "APP_VERSION=0.1.0-${GITHUB_REF_NAME//[^a-zA-Z0-9]/}.${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Package Helm Chart for Replicated
      id: package-helm-chart
      run: |
        mkdir -p manifests
        helm package ./gitea -u -d manifests \
          --app-version=0.0.1-${{ github.ref_name }} \
          --version=${{ env.APP_VERSION }}

    - name: Smoke Test
      id: smoke-test
      uses: replicatedhq/compatibility-actions/smoke-test@v0
      with:
        app-slug: ${{ secrets.REPLICATED_APP }}
        api-token: ${{ secrets.REPLICATED_API_TOKEN }}
        yaml-dir: manifests
        kubernetes-distribution: ${{ matrix.cluster.distribution }}
        kubernetes-version: ${{ matrix.cluster.version }}
        installation-method: helm
        test-script: ./tests/test.sh
        helm-chart-name: gitea
        # helm-values: |
        #   image:
        #     tag: latest

